name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 355 # Slightly less than 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to biralo
        run: sudo hostnamectl set-hostname biralo

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch zip

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore backup files
        run: |
          if [ -f ./backup/backup.zip ]; then
            echo "Restoring VPS backup..."
            unzip -o ./backup/backup.zip -d /
          else
            echo "No backup found, starting fresh."
          fi

      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"

      - name: Create user biralo with sudo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Show Tailscale IP
        run: |
          echo "🔗 Tailscale IPv4:"
          tailscale ip -4 || echo "Tailscale IP not found"

      - name: Sleep to keep VPS alive
        run: sleep 21000 # ~5.83 hours

      # -------------------------------
      # BACKUP SECTION (Always runs)
      # -------------------------------
      - name: Backup VPS data and tailscale state
        if: always()
        run: |
          echo "Saving VPS state..."
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/ || true
          sudo mkdir -p /opt/vps-backup/home
          sudo rsync -a --delete /home/biralo/ /opt/vps-backup/home/biralo/
          sudo mkdir -p /opt/vps-backup/root
          sudo rsync -a --delete /root/ /opt/vps-backup/root/
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup

      - name: Upload VPS backup artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
